// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Gauge

#ifndef _GAUGE_UI_H
#define _GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SpeedometerScreen.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_main_background2x_png);    // assets/Main Background2x.png
LV_IMG_DECLARE(ui_img_cat_background2x_png);    // assets/Cat Background2x.png
LV_IMG_DECLARE(ui_img_cat_measure2x_png);    // assets/Cat Measure2x.png
LV_IMG_DECLARE(ui_img_cat_needle2x_png);    // assets/Cat Needle2x.png
LV_IMG_DECLARE(ui_img_gforce_gauge2x_png);    // assets/GForce Gauge2x.png
LV_IMG_DECLARE(ui_img_fire_baclground2x_png);    // assets/Fire Baclground2x.png
LV_IMG_DECLARE(ui_img_fire_measure2x_png);    // assets/Fire Measure2x.png
LV_IMG_DECLARE(ui_img_fire_needle2x_png);    // assets/Fire Needle2x.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
