// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Gauge

#include "ui.h"

lv_obj_t * ui_SpeedometerScreen = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Background = NULL;
lv_obj_t * ui_Measure = NULL;
lv_obj_t * ui_Needle = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_SpeedLabel = NULL;
// event funtions

// build funtions

void ui_SpeedometerScreen_screen_init(void)
{
    ui_SpeedometerScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SpeedometerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_SpeedometerScreen);
    lv_img_set_src(ui_Image8, &ui_img_main_background2x_png);
    lv_obj_set_width(ui_Image8, lv_pct(273));
    lv_obj_set_height(ui_Image8, lv_pct(273));
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background = lv_img_create(ui_SpeedometerScreen);
    lv_img_set_src(ui_Background, &ui_img_cat_background2x_png);
    lv_obj_set_width(ui_Background, LV_SIZE_CONTENT);   /// 447
    lv_obj_set_height(ui_Background, LV_SIZE_CONTENT);    /// 482
    lv_obj_set_align(ui_Background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Background, 520);

    ui_Measure = lv_img_create(ui_SpeedometerScreen);
    lv_img_set_src(ui_Measure, &ui_img_cat_measure2x_png);
    lv_obj_set_width(ui_Measure, LV_SIZE_CONTENT);   /// 447
    lv_obj_set_height(ui_Measure, LV_SIZE_CONTENT);    /// 448
    lv_obj_set_align(ui_Measure, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Measure, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Measure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Measure, 520);

    ui_Needle = lv_img_create(ui_SpeedometerScreen);
    lv_img_set_src(ui_Needle, &ui_img_cat_needle2x_png);
    lv_obj_set_width(ui_Needle, LV_SIZE_CONTENT);   /// 223
    lv_obj_set_height(ui_Needle, LV_SIZE_CONTENT);    /// 224
    lv_obj_set_align(ui_Needle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Needle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Needle, 2300);
    lv_img_set_zoom(ui_Needle, 520);

    ui_Image7 = lv_img_create(ui_SpeedometerScreen);
    lv_img_set_src(ui_Image7, &ui_img_gforce_gauge2x_png);
    lv_obj_set_width(ui_Image7, lv_pct(100));
    lv_obj_set_height(ui_Image7, lv_pct(100));
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 228);

    ui_SpeedLabel = lv_label_create(ui_SpeedometerScreen);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, 97);
    lv_obj_set_y(ui_SpeedLabel, 59);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "");
    lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_SpeedometerScreen_screen_destroy(void)
{
    if(ui_SpeedometerScreen) lv_obj_del(ui_SpeedometerScreen);

    // NULL screen variables
    ui_SpeedometerScreen = NULL;
    ui_Image8 = NULL;
    ui_Background = NULL;
    ui_Measure = NULL;
    ui_Needle = NULL;
    ui_Image7 = NULL;
    ui_SpeedLabel = NULL;

}
