// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Gauge

#ifndef UI_SPEEDOMETER_H
#define UI_SPEEDOMETER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Speedometer
extern void ui_Speedometer_screen_init(void);
extern void ui_Speedometer_screen_destroy(void);
extern lv_obj_t * ui_SpeedometerScreen;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_Measure;
extern lv_obj_t * ui_Needle;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_SpeedLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

