// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Gauge

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Background1 = NULL;
lv_obj_t * ui_Measure1 = NULL;
lv_obj_t * ui_Needle1 = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image1, &ui_img_main_background2x_png);
    lv_obj_set_width(ui_Image1, lv_pct(273));
    lv_obj_set_height(ui_Image1, lv_pct(273));
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Background1, &ui_img_fire_baclground2x_png);
    lv_obj_set_width(ui_Background1, LV_SIZE_CONTENT);   /// 447
    lv_obj_set_height(ui_Background1, LV_SIZE_CONTENT);    /// 482
    lv_obj_set_align(ui_Background1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Background1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Background1, 520);

    ui_Measure1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Measure1, &ui_img_fire_measure2x_png);
    lv_obj_set_width(ui_Measure1, LV_SIZE_CONTENT);   /// 447
    lv_obj_set_height(ui_Measure1, LV_SIZE_CONTENT);    /// 448
    lv_obj_set_align(ui_Measure1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Measure1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Measure1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Measure1, 520);

    ui_Needle1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Needle1, &ui_img_fire_needle2x_png);
    lv_obj_set_width(ui_Needle1, LV_SIZE_CONTENT);   /// 223
    lv_obj_set_height(ui_Needle1, LV_SIZE_CONTENT);    /// 224
    lv_obj_set_align(ui_Needle1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Needle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Needle1, 2300);
    lv_img_set_zoom(ui_Needle1, 520);

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_gforce_gauge2x_png);
    lv_obj_set_width(ui_Image2, lv_pct(100));
    lv_obj_set_height(ui_Image2, lv_pct(100));
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 228);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image1 = NULL;
    ui_Background1 = NULL;
    ui_Measure1 = NULL;
    ui_Needle1 = NULL;
    ui_Image2 = NULL;

}
