// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Gauge

#include "../ui.h"

// COMPONENT Dropdown1

lv_obj_t * ui_Dropdown1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Dropdown1;
    cui_Dropdown1 = lv_dropdown_create(comp_parent);
    lv_dropdown_set_options(cui_Dropdown1, "Cat\nFire\nHypersport");
    lv_obj_set_width(cui_Dropdown1, lv_pct(88));
    lv_obj_set_height(cui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Dropdown1, -1);
    lv_obj_set_y(cui_Dropdown1, -175);
    lv_obj_set_align(cui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DROPDOWN1_NUM);
    children[UI_COMP_DROPDOWN1_DROPDOWN1] = cui_Dropdown1;
    lv_obj_add_event_cb(cui_Dropdown1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Dropdown1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Dropdown1_create_hook(cui_Dropdown1);
    return cui_Dropdown1;
}

