// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Gauge

#ifndef _UI_COMP_DROPDOWN1_H
#define _UI_COMP_DROPDOWN1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Dropdown1
#define UI_COMP_DROPDOWN1_DROPDOWN1 0
#define _UI_COMP_DROPDOWN1_NUM 1
lv_obj_t * ui_Dropdown1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
